all:
	gcc main.c -lm -lncurses -o gen_font

#install dependency libraries on debian-based systems:
#apt-get update
#apt-get install libncurses5-dev libncursesw5-dev

#install dependency libraries on redhat-based systems:
#"yum install ncurses-devel" or "dnf install ncurses-devel"